### ISSUE TITLE
order placeNames in places

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#119]
order based on xmlid numbering, then xml lang than alt

**Comment by PietroLiuzzo** [comment]
suggestion from Francesca in email

e.g. LOC1452Angara.

this is a possible order
 ID1 (traslitterazione corripondente)
Alt/ID2 (traslitterazione corrispondente, se presente)
etc.

Esempio
* Āngarab - አንገረብ (gez)
* Small Āngarab (alt)

**Comment by eu-genia** [comment]
NB @FrancescaPanini initial alef is still missing, and the first A is first order (አ short): ʾAngarab

better: 
ʾAngarab (አንገረብ [amh]) 
alt: Small ʾAngarab 

- in this case btw the language is NOT Geez but Amharic

**Comment by FrancescaPanini** [comment]
Hello
Pietro's email is from the 12 August, before our meeting, that is why it reflects a wrong spelling (ie Āngarab). I amended the record for ʾAngarab last week so it is now correct, hopefully.

Thanks
Francesca

**Comment by eu-genia** [comment]
yes, sorry, is correct: one other remark though: rivers cannot have the same coordinates as towns, they are long, we should discuss how and whether to insert the coordinates for things like rivers, regions, etc. in this case the river is not even in the town of Gondar

**Comment by FrancescaPanini** [comment]
Yes, agreed. For regions and other areas, the idea was to use multiple points in order to define a polygone. For something like a river, I guess that a line could be defined as Open Street Map does. 

What I am struggling with is finding the coordinates though. I am struggling finding them in the Gazeteer or online so, as a first step, I approximate them marking their certainty as medium or low: in this case the record refers to the Small ʾAngarab that flows along the border of the historic town of Gondar so I used the same coordinates as Gondar, but it is certainly not accurate.

**Comment by PietroLiuzzo** [comment]
order changed in app as per requests and discussion. coordinates can be found on wikipedia, openstreetmap, geonames, geohack etc.
