### ISSUE TITLE
Ge'ez in titles

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#126]
Since the names of places and persons are written in ge'ez in the files, should the same be done for the titles of works in the work records?

**Comment by PietroLiuzzo** [comment]
not necessarily in my opinion, especially if the source being digitized does not report such title in Geez. as of #116 there will be a small tool to facilitate conversions in the future. you will be able to input a text in a declare translitteration or script and transform it to another of the desired output. e.g. if you have a translitterated title and want to add the corresponing Ge'ez you will select input type and output to obtain the desired result.

**Comment by eu-genia** [comment]
nb  automated transliterations/retransliterations do not always work esp. in the cases of geminations. so one will have to correct carefully if one does anything automatically.
works with circulation in Ethiopia that do have an Ethiopic title or a label should, like persons and places, have their primary title t1 in fidel and a normalized corresp in transcription.

**Comment by PietroLiuzzo** [comment]
What does "in fidel" means?

Am 22.08.2016 11:19 schrieb "eu-genia" <notifications@github.com>:

**Comment by thea-m** [comment]
@PietroLiuzzo in Ethiopic script

So the titles would be entered like this?:

```
<titleStmt>
            <title xml:id="t1">ውዳሴ፡ ማርያም</title>
            <title corresp="#t1" type="normalized">Wǝddāse  Māryām </title>
            <title  xml:id="t2">ውዳሴ፡ እግዝእትነ፡ ማርያም፡ ድንግል፡ ወላዲተ፡ አምላክ</title>
            <title corresp="#t2" type="normalized">Wǝddāse ʾǝgzǝʾtǝna Māryām dǝngǝl walādita ʾamlāk </title>
         </titleStmt>
```

**Comment by eu-genia** [comment]
@PietroLiuzzo  fidel (actually fidal, ፊደል) = Ethiopic script
@thea-m looks good to me

**Comment by PietroLiuzzo** [comment]
thanks @eu-genia! that clarifies a lot!

copying part of conversation via skype with @thea-m 

schema reports on the above the following error title in work must always have an @xml:id which identifies alternative titles and @ref for the titles in other languages translating each of the given titles. Format of the id should be like t1 t2, etc.

needs 
* normalization of practices with what is beeing done for persons and places
* probably parametrization of schema rule for title in titleStmt so that @corresp is used here and ref when pointing to a work record.

**Comment by PietroLiuzzo** [comment]
the schema now handles this as desired. in titleStmt, as in place records and person records the element can take alternatively xml:id or corresp, whereas in msItem a ref and/or an xml:id are required.
