### ISSUE TITLE
attributes with empty values

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#130]
@eu-genia @MassimoVilla @DenisNosnitsin1970 @thea-m @sologebre @FrancescaPanini , 

Please, check that your files do not contain attributes with empty values like 

     <element attribute="">content</element>

or

     <element attribute=""/>

There is no good reason to add an attribute without a value. 

If the value is not known simply do not add the attribute. 

If the missing value is for example an id, go ahead and add it in the list in the google file before you enter the entry. 

I understand if it is work in progress off course, that is no problem, but as a note of caution, please, try to make sure you don't leave too much of that behind and if you do, rather don't tag things and add a comment (`<!--comment-->`) in the file that something needs to be checked instead of leaving the file invalid.

practical examples I have found occur in `placeName`, `persName`, `locus`, `desc`, `date`.

in locus and date, you don't need to enter both `@to` and `@from` or `@notBefore`, `@notAfter`, you can enter just one if the other is not known. 

To find all such instances simply validate your files. you can select them all and with the validate option in the secondary click options, run the validation on all your files.

If there is a good reason for that I am happy to modify the rule in schema requiring a ref in `persName`s and `placeName`s so that it does not require a `@ref` but only recommend it.

**Comment by eu-genia** [comment]
I can see many empty "" in ES-files (esp. with locus) but I have not been through them - this was the result of the original conversion. I can go through them gradually but it will take a while.
I think ref must be requested for persName/placeName, as otherwise we risk that we relax and do not create IDs we might need later anyway.
locus for decoNotes must be relaxed, as we have discussed, some decoNotes contain general description of the decoration of the entire manuscript and can have no locus

**Comment by PietroLiuzzo** [comment]
sorry, this was obviously meant only about newly created files, not the batch conversion.

**Comment by PietroLiuzzo** [comment]
Dear all, 

even worst is this kind of entry. 

     @ref="..." 

here again, please omit the attribute and leave a comment for further tagging.
