### ISSUE TITLE
calendar type

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#163]
@thea-m is already working on a list of calendar types to be added to the schema for the attribute @calendar in `date`.

**Comment by thea-m** [comment]
I think we could use:

ʿĀmata ʿālam/ʿĀmata ʾəm-fəṭrat (Era of the World)
ʿĀmata śəggāwe (Era of the Incarnation – Ethiopian)
ʿĀmata məḥrat (Era of Grace)
ʿĀmata samāʿtāt (Era of Martyrs (Diocletian))
Hiǧrī (Islamic)
Gregorian, Julian

(ʿĀmata śəggāwe and ʿĀmata samāʿtāt can also be called ʿĀmata məḥrat..when unsure which era is meant, it would maybe be better not to have an attribute instead of risking the wrong one)

Did I confuse or miss something? @sologebre @MassimoVilla

**Comment by MassimoVilla** [comment]
I remember that in some lengthy colophons the Era of Alexander the Great is also used together with the others for the sake of completeness.

**Comment by sologebre** [comment]
Yes, it is right. The Era of Alexander the Great is used also in the
colophon of the chronicle of King Gälawdewos

**Comment by PietroLiuzzo** [comment]
Please do let me know when this list is complete

**Comment by thea-m** [comment]
There are actually many more eras (see for instance the colophons in BLadd16220, BLadd16257 or BNFet110) such as:
Birth of the Virgin, Conversion of Ethiopia, Martyrs of Antiochia, Council of Nicea, Era of the Hebrews, Era of Judith, Eras of Byzantium and Rome...
(Neugebauer 1979: 124 suggests those in BLadd16220 are ad hoc inventions)
Do you think we should add all of them to the schema? I think adding the more common ones and marking all other dates simply with `<date>` as we do now would be enough.

**Comment by thea-m** [comment]
I would suggest adding:

- ʿĀmata ʿālam/ʿĀmata ʾəm-fəṭrat (Era of the World)
- ʿĀmata śəggāwe (Era of the Incarnation – Ethiopian)
- ʿĀmata məḥrat (Era of Grace)
- ʿĀmata samāʿtāt (Era of Martyrs (Diocletian))
- Era of Alexander
- Evangelists' years
- Hiǧrī (Islamic)
- Julian
- Gregorian 
- Other

(As a matter of fact, do we write AD or CE?)

**Comment by PietroLiuzzo** [comment]
I am adding these to the list.
not gregorian, as that is the default 
neither other, as the information is not meaningful and the list is open, thus another calendar can simply be named
