### ISSUE TITLE
Problem with Transcription Files 

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [SChAth/ScAthiop#2281]
As you will recall I changed the facsimile and text files for a set of 5 of the magic scrolls last week, having revised the way that I used the conversion file transkribus2BM. All of those files are now not visible and have the following error:

![image](https://user-images.githubusercontent.com/39619238/204251827-ad24ec85-6fa5-48c7-9673-ae5362f4046f.png)

The files not corrected don't have this error. I didn't edit the record file, only replaced the facsimile and text files. Any ideas?

**Comment by eu-genia** [comment]
yes this always happens when merging files with xincluded parts for the moment, several versions are created on the backend with the same xml:id, i always clean manually but i forgot last week, sorry, will do now.
hopefully we shall soon have a new system in place so that this won't happen in the future.
