### ISSUE TITLE
Missing EMIP Records 

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [SChAth/ScAthiop#2659]
EMIP records from EMIP02746-3000,  3001-3071, 3092-3111 are missing. These correspond to most of the UNESCO image sets that Steve Delamarter supplied images for - but here there are not even the records. Any thoughts?

**Comment by eu-genia** [comment]
As discussed with Steve, I have merged records for manuscripts that were already in Bm, in particular EMML or other similar cases, in order to avoid cataloguers doing double work.
Wherever the EMIP spreadsheet specified that the shelfmark for the manuscript already exists, the old shelfmark has been used as the stable identifier. 
The merge is recorded in the formerlyAlsoListedAs relation which shows here https://betamasaheft.eu/deleted.html
You can get there as, when calling the deleted ID, you are suggested to go to the deleted list
![image](https://github.com/user-attachments/assets/2bff8793-6eb8-449c-ad19-e5c472c14db2)

I hope you understand that as a single project we cannot afford having the same manuscript listed several times.

Different digital copies of the same manuscript should be encoded in the record ideally as shown here https://github.com/BetaMasaheft/Documentation/issues/2514, as the shelfmark of a manuscript (the objects we produce descriptions for) is not the same as the identifier of a microfilm or a photoset.

Hopefully in the new release we shall be able to have the function developed where the relation `formerlyAlsoListedAs  `triggers a redirect. @HelenaSabel we have discussed it with @line-o at some point, but I do not know how complex it might be. 
https://github.com/BetaMasaheft/Documentation/issues/1864
https://github.com/BetaMasaheft/Documentation/issues/1511
https://github.com/BetaMasaheft/Documentation/issues/1569

**Comment by eu-genia** [comment]
See also https://github.com/BetaMasaheft/Documentation/issues/2284

**Comment by Ralph-Lee-UK** [comment]
Thank you. All clear.
