### ISSUE TITLE
Art theme for Devil

### ISSUE THREAD

**Issue by karljonaskarlsson** [SChAth/ScAthiop#2661]
There is a full-page drawing of a devil/demon in the manuscript Uppsala, O Etiop. 29: https://www.alvin-portal.org/alvin/imageViewer.jsf?dsId=ATTACHMENT-0074&pid=alvin-record:490723

I cannot find any art theme for this kind of depiction, but it feels like one could be useful. Do you agree? Can I go ahead and create one?

@eu-genia @CarstenHoffmannMarburg @nafisa-valieva

**Comment by CarstenHoffmannMarburg** [comment]
I wonder, why I did not receive a notification via email even though Jonas has tagged me?

**Comment by CarstenHoffmannMarburg** [comment]
I cannot find a ArtTheme for Devil and I agree, that a new ArtTheme could be created. What we have is 'Demon', which could be suitable for this case as well, if it is not certain, that it is precisely Satan, who was depicted.

**Comment by karljonaskarlsson** [comment]
Thank you for noticing "Demon"! I had overseen it, but I think it works well in this case, as the drawing has no caption that allows us to identify the "person".

**Comment by karljonaskarlsson** [comment]
It seems like what we have is an "art keyword" for "demon", but no "art theme". What do you say about creating one?

**Comment by eu-genia** [comment]
I just wonder if there is a reason why @gnizla did not create it when the art themes were launched - could the reason be that this is not an art theme representative of Ethiopian art? The drawing does not look Ethiopian at all to me.

**Comment by eu-genia** [comment]
I would not create art themes for subjects of miniatures not present in Ethiopian tradition. Do we have other cases?

**Comment by gnizla** [comment]
Thanks, when I set up the AT, I just set up a system to encode them and included the most common ones, but by no means all, so there will be room for creating/encoding more.

However, I do agree with Genia, that this doesn't look "Ethiopian" and you will need to think if it is any benefit setting this up as a Art Theme rather than just employing the keyword demon to describe it.

One good way to think about whether something deserves an art theme is whethere there is a clear literary source for it in the Ethiopian tradition and what's the best way to describe it. When it comes to manuscripts, I am not familiar with portraits of demons that are comparable (e.g. to the portraits of Holy Men for which we have an AT). Demons usually appear in scenes such as the Anastasis and Last Judgement. Here, it is best to use the keyword demon to describe their presence within a scene that has a clearly identifiable source.

A counter argument to this is the presence of demon-looking figures on some magic scrolls. These could be described as portraits. You could have a separate AT for them, but the risk here is that you might have to perform different searches for AT demon and Keyword demon. Is that really beneficial to the end-user? That's the question I would ask myself. My feeling is that they keyword "demon" could achieve the same classificatory purpose, but it's a judgement call for the BM team.

**Comment by karljonaskarlsson** [comment]
Ok, I will use the keyword for now at least! Thank you!
