### ISSUE TITLE
Works in BAVet114 and BAVet118

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#2684]
I would like to open a branch with the following aims:
- correct ኩብራት with ክቡራት in the incipit of LIT7126Asmat, as rightly pointed out by @karljonaskarlsson 
- create a work record for a text On the persecution of the Jacobite Christians at the time of the Jesuits, as found in BAVet114#i3. Incipit: `ንጽሕፍ፡ ተዝካረ፡ ነገር፡ ጥዩቅ፡ ወዜና፡ ጽዱቅ። በእንተ፡ ዘኮነ፡ ስደት፡ ዓቢይ፡ ላዕለ፡ ክርስቲያን፡ ያዕቆባውያን፨ እለ፡ ብሔረ፡ ኢትዮጵያ፨` The text is also found in BNFabb225, but the MS record does not exist yet (or is it in some hidden branch? Someone knows?)
- create a work record for a small note On the restoration of the Solomonic dynasty, as found in BAVet114#i8. The entire text is: `በስመ፡ አብ፡ ... ወበውእቱ፡ መዋዕል፡ በዘመነ፡ መንግሥቶሙ፡ ለአቡነ፡ ተክለ፡ ሃይማኖት፡ እምድኅረ፡ ብዙኅ፡ ዓመታት፡ እምዘ፡ ተኃይደት፡ መንግሥቶሙ፡ ለ፳ኤል፡ አመ፡ ፲ወ፯ለሐምሌ፡ አግብአ፡ እግዚአብሔር፡ እምነገደ፡ ሔጳፃ፡ ለይኵኖ፡ አምላክ፡ እስራኤላዊ፨ ወኮነ፡ ሰላም፡ ወዛኅን፡ ላዕለ፡ ኵሉ፡ በሐውርት፡ ጸሎቱ፡ ወበረከቱ፡ ለአቡነ፡ ተክለ፡ ሃይማኖት፡ የሃሉ፡ ምስለ፡ መምሕርነ፨ ገብረ፡ ሥላሴ፡ ለዓለመ፡ ዓለም፡ አሜን።`
- create a work record for a "Prayer of the lover" found in BAVet118#a1 (incipit: `ጸሎተ፡ <sic>ምስተፋቅር፨</sic> አስማተ፡ ንዋይ፡ ምስሓበ፡ ንዋይ፨ አስተፋቅር፡ ወአስተዋድድ፡ ወአስተሳልም፨`) and in BAVet128#a33 (incipit: `በስመ፡ አብ፡ ... ጸሎተ፡ መስተፋቅር፡ አስማተ፡`), yet without ID here.
- create a work record for a short divinatory text in BAVet118#i7. Incipit: `<sic>ሓሳበ፡</sic> <sic>ፊደላተ፨</sic> <sic>ወጠልሰማተ፡</sic> ዘተረክበ፡ እምደሴተ፡  ፃና፨ ለእመ፡ <sic>ተሓውር፡</sic>  ውስተ፡ ቤተ፡ መንግሥት፨`

**Comment by nafisa-valieva** [comment]
I have no objections on my behalf! I  do not think that BNFabb225 was created. If On the persecution of the Jacobite Christians at the time of the Jesuits was edited and you want to have a stub for BNFabb225, you can create it or I can create it for you. Otherwise I would prefer to wait till BNFabb225's time comes, not to confuse things.

**Comment by MassimoVilla** [comment]
Thank you @nafisa-valieva . I wouldn't personally create a stub for that MS. I can add a specific comment in the new work record with reference to BNFabb225.

**Comment by nafisa-valieva** [comment]
> Thank you @nafisa-valieva . I wouldn't personally create a stub for that MS. I can add a specific comment in the new work record with reference to BNFabb225.

the question is only whether the manuscript was used in the edition or not. If is was not and you want to indicate its attestation in the manuscript, I / Denis will just use the Lit id you create and in this way the manuscript will be connected. At least this is how I see it!

**Comment by CarstenHoffmannMarburg** [comment]
I think, it is useful to have a stub for BNFabb225, so Massimo can refer more easily to it.

I cannot see ኩብራት any text in the record of [LIT7126Asmat](https://betamasaheft.eu/LIT7126Asmat.xml). I think, it is not merged, yet. 

I am OK with the creation of a new CAe for "On the persecution of the Jacobite Christians at the time of the Jesuits".

I am not convinced about a new CAe for the small note entitled "On the restoration of the Solomonic dynasty". If there is no other attestation, we cannot proof any independant circulation and therefore, we should create a new CAe for it. The content may be derived from the Kəbra Nagaśt or any other chronology. If you can fix it more precisely to a certain source text, it is reasonable to create a CAe, otherwise I think, it is better to leave in unmarked.

For the "prayer of the lover", I think, it is OK to count both witnesses as one work. BAVet128#a33:
![grafik](https://github.com/user-attachments/assets/4cf0425c-40bd-4853-91db-982298a05e77)

**Comment by nafisa-valieva** [comment]
ok, I will create a stub for BNFabb225 then!

**Comment by CarstenHoffmannMarburg** [comment]
@nafisa-valieva 
> ok, I will create a stub for BNFabb225 then!

I think, we have a server down at the moment. Please do not create a branch from master without checking, if the website is online!

**Comment by nafisa-valieva** [comment]
> @nafisa-valieva
> 
> > ok, I will create a stub for BNFabb225 then!
> 
> I think, we have a server down at the moment. Please do not create a branch from master without checking, if the website is online!

you mean that I can't create it from my branch even?

**Comment by eu-genia** [comment]
@nafisa-valieva @CarstenHoffmannMarburg you can always work in GitHub/Oxygen/your branch. You can ALWAYS create branches as working on GitHub is NOT connected with the betamasaheft.eu application.
The two ONLY get synchronized when pull requests are merged, so only before merging a pull request it is important to check that the betamasaheft.eu application is online.

**Comment by MassimoVilla** [comment]
I logged in and created a new Work record for the work "On the persecution of the Jacobite Christians at the time of the Jesuits", and I got, once again, an exceptionally high number: LIT14518Jacobite. What did I do wrong @eu-genia ?

**Comment by eu-genia** [comment]
Please rename to LIT7136Jacobite 

Sometimes on rebooting some indexing error happens and the app thinks 14517 exists somewhere. I have to remember to reindex on each reboot... 

https://github.com/BetaMasaheft/Documentation/issues/2694

**Comment by eu-genia** [comment]
(Should be OK now)

**Comment by MassimoVilla** [comment]
Thank you, now numbering works properly!
