### ISSUE TITLE
Coherent use of listWit in LIT-records

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [SChAth/ScAthiop#2690]
@eu-genia 

@karljonaskarlsson, @nafisa-valieva and me, we came across, that the use of listWit in sourceDesc is often different in some workrecords. According to the [guidelines](https://betamasaheft.eu/Guidelines/?q=listWit&id=work-teiHeader), the listWit we should `use <witness>[↗](https://betamasaheft.eu/Guidelines/?id=witness) for those manuscripts which are used for the edition we are going to provide in the <div type='edition'>[↗](https://betamasaheft.eu/Guidelines/?id=div). All manuscript records containing the work are displayed in the app anyway.`

But in some LIT records I have worked with, listWit is used to mention every witness, or every witness considered relevant, as in LIT1295Dersan, for example. (See https://github.com/BetaMasaheft/Works/pull/1314). Is it correct to use listWit to document all known or relevant witnesses? If not, should the existing records be systematically corrected, or at least when we come across such a case?

There is also an ambivalence in the phrase "those manuscripts which are **used** for the edition". Does this mean, that the manuscript, that is primarily used for an edition of a work shall be noted (as for LIT1295Dersan, this would be BMLacq776)? Or is it rather correct or acceptable to mention all manuscripts, which are mentioned in the record (as is the case for BAVet82, BAVet121 and BLorient691 in the record of LIT1295Dersan?

**Comment by eu-genia** [comment]
Originally, TEI was developed for editing texts. In such case, the `text `section of the XML file MUST contain the **CRITICAL EDITION** of a work and the `sourceDesc `list the witnesses used with sigla as `xml:id` to be able to refer to them in the apparatus and the bibliography, as has been shown during the Summer School. This is what TEI guidelines imply. You must have the item, and you must assign xml:id, to be able to refer to an item.

In our case we in most cases do not provide at the moment critical editions. But we sometimes refer to certain manuscripts when describing a work, in which case the same rule applies.

In an ideal case, all manuscripts are already described in the system with a `ref `in `title `of a `msItem`, making the witness list redundant. BUT we seldom have the ideal case when all known witnesses of a known work have already been fully and properly encoded. In order to compensate for this world which will always remain far from ideal when we know that there exists a witness of a work we should preferably list it among the witnesses to make sure that the information is available also in cases when the manuscript record has not been properly encoded yet.

**Comment by nafisa-valieva** [comment]
> Originally, TEI was developed for editing texts. In such case, the `text `section of the XML file MUST contain the **CRITICAL EDITION** of a work and the `sourceDesc `list the witnesses used with sigla as `xml:id` to be able to refer to them in the apparatus and the bibliography, as has been shown during the Summer School. This is what TEI guidelines imply. You must have the item, and you must assign xml:id, to be able to refer to an item.
> 
> In our case we in most cases do not provide at the moment critical editions. But we sometimes refer to certain manuscripts when describing a work, in which case the same rule applies.
> 
> In ideal case, all manuscripts are already described in the system with a `ref `in `title `of a `msItem`, making the witness list redundant. BUT we seldom have the ideal case when all known witnesses of a known work have already been fully and properly encoded. In order to compensate for this world which will always remain far from ideal when we know that there exists a witness of a work we should preferably list it among the witnesses to make sure that the information is available also in cases when the manuscript record has not been properly encoded yet.

In this case it would be better to have the Guidelines explaining this practice too. Definition of witnesses that appears on web as ´Manuscripts used in this edition´ needs to be modified too. I won´t take responsibility for changing the guidelines because I find this practice very unfortunate. I would prefer to have too different ways, one for proper witnesses used in editions, another for manuscripts attesting works, but not described in the database. I would also like to have Alessandro Bausi´s @abausi opinion on this matter. From little i have seen, most of the LIT records do not have listWit at all, which means we can still have a common practice and follow it, I hope! I would also suggest adding a statement / a note on whether the text was edited or not.

**Comment by eu-genia** [comment]
I have updated the guidelines already. The correction is documented in this issue.
I will update the visualization.
We have very few perfect LIT records, so for all of them we do what we can on a case by case basis.

**Comment by eu-genia** [comment]
I do not think it makes sense to have three lists (one automatically extracted in the orange box, one created through present listWit, and one more elsewhere?), our interface is already very confusing as is  

Yet on checking the code I see that actually "`Manuscripts used in this edition`" should only be printed if there is `@rend="edition"` as an attribute to listWit, so the distinction is already there, I will check why the application does not act properly, actually there should be no "`Manuscripts used in this edition`" subtitle visible, just the text "`The following manuscripts are reported in this record as witnesses of the source of the information or the edition here encoded`".

So if one has an edition one whould have `listWit rend="edition"`, if you simply list witnesses you do not use `rend="edition"`, I am re-updating the guidelines to explain this

**Comment by eu-genia** [comment]
the code has been updated to make sure that the "Manuscripts used in the edition" is only printed when `rend="edition"` is provided

**Comment by eu-genia** [comment]
As already mentioned during the meeting, everyone is welcome to enhance and develop work, manuscript, and places records by
- adding bibliography
- adding relations
- adding witnesses
and adding anything else you might need for your work. 
Again, in an ideal world we have all manuscripts properly encoded with all msItems linked to the correct IDs and then we have all works listing all manuscript witnesses.
In our case for most works we have neither manuscripts pointing to them nor manuscripts listed as witnesses.
Whenever we encounter a work record we have time and wish and necessity to enhance we try to improve it as much as we can. We will never ever be perfect. So there is no way we can have all 7300 CAe Ids listing all manuscript testimonies. 
All this unfortunately can only happen on a case by case basis. 

Thank you for helping us improve our guidelines; as in many other cases they should be refined.

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 I think you have missed this discussion
