### ISSUE TITLE
The tab "Clavis Aethiopica (Works)" not functional?

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [SChAth/ScAthiop#2701]
It appears that the tab "Clavis Aethiopica (Works)", which is unfolded if one clicks upon the brown bar above on the surface of the app, does not work and is not functional. But if one scrolls down, the option "Clavis Aethiopica" under "Texts" works. Can smth be done about the upper tab "Clavis Aethiopica (Works)" (to be fixed, or removed, interlinked, whatever), on the long run? It is very good that there is a functional option to get the list of work IDs at once, but I am sure that only one 1 or 2 out of 10 users will come to the idea idea to scroll down, most will hang on one the first obvious option.

**Comment by eu-genia** [comment]
Dear @DenisNosnitsin1970 

1) please only assign as assignees those who must do something to fix the issue; others may be tagged in the discussion. Thank you. The rule is always one issue = one responsible person (assignee).

2) it is important for practical issues to exactly describe what you get and what you want to get and where.
In my browser in the main page when I click on "Texts" in the main line
![image](https://github.com/user-attachments/assets/96fdd787-0c86-417e-903d-3921e939692d)
I am taken to `https://betamasaheft.eu/#texts` which is an ancor on the very same page (you can also scroll down, but the ancor makes it faster) 
![image](https://github.com/user-attachments/assets/5b6909e6-6d3e-4615-8eff-db9eb99ab108)
Here you can then choose on what to click further. I had changed here the Clavis link to the static list.

You probably are speaking about the upper navigation 
![image](https://github.com/user-attachments/assets/3fdb0176-52a1-4e7c-9106-feb2623ed5aa)


where I had not thought about updating the referral link which still points to the dynamic https://betamasaheft.eu/works/list - the dynamic link indeed sometimes does not work as it is enough to have one error somewhere in one file and the whole search results cannot be generated. I will update this with the static link as well. I simply never use the upper navigation so did not think about this here https://github.com/BetaMasaheft/Documentation/issues/2697
It would have been much easier if you simply exactly could show where you click and which error you get. It took me a while to understand that you are complaining about `https://betamasaheft.eu/works/list` pointed from the navigation bar and not about `https://betamasaheft.eu/#texts`.

3) When you see an error anywhere in the app like the one currently appearing when trying to call the dynamic list at https://betamasaheft.eu/works/list
```
An error has occurred
something has gone wrong. Sorry! This error has been generated by the application.

err:XPTY0004 Grouping variable t evaluates to more than one item [at line 1542, column 23, source: /db/apps/BetMasWeb/modules/app.xqm]
In function:
	app:paginateNew(node(), map(*), xs:int, xs:int, xs:int, xs:int) [-1:-1:/db/apps/BetMasWeb/modules/app.xqm]

```
see also https://github.com/BetaMasaheft/Documentation/issues/2696 
please always create an issue marked `bug `so that I can try and find out where the error comes from. The error is in XML, not in the application. 
Thank you for your help in making this all work

**Comment by eu-genia** [comment]
OK I discovered the bug, the same file was saved twice in different folders, and the app cannot process if the same clavis number is used for more than one XML. Now it should be OK whichever way.
