### ISSUE TITLE
Description of MS BL Orient. 720 not available (error occurred)

### ISSUE THREAD

**Issue by vitagrazia81** [SChAth/ScAthiop#2721]
Dear @eu-genia,
I need to use the link of this description for a paper, but the link is not functioning, it shows an error when I try to access it. Is there any way to resolve the issue? 
Thank you.
Vita
Here the  link https://betamasaheft.eu/manuscripts/BLorient720/main

**Comment by eu-genia** [comment]
It is always helpful if you copy the error so that I can see what is wrong

`HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/manuscripts/BLorient720/main: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: string($arg as item()?) xs:string. Expected cardinality: zero or one, got 2. [at line 2219, column 13, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:layoutdimensionunit(item()*) [2257:34:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:layout(item()*) [2027:17:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:layoutDesc(item()*) [4426:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5630:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5686:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4462:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5571:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5883:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1434:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [565:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]
`

This error shows me that there is something wrong with the element for layout dimensions (can be only once, are given more than once).

Indeed, opening the record I see

```
<layoutDesc>
                                <layout columns="2" writtenLines="13">
                                    <ab type="pricking">Pricking and ruling are visible.</ab>
                                    <ab type="pricking">Primary pricks are visible, horizontal pricks are visible.</ab>
                                    <ab type="ruling" subtype="pattern">1A-1A-1A1A/0-0/0-0/C</ab>
                                    <ab type="ruling">The upper line is written above the ruling,
                                        the lower line is written above the ruling.</ab>
                                        <dimensions unit="mm">
                                          <height>202</height>
                                          <width>192</width>
                                        </dimensions>
                                        <dimensions type="margin" unit="mm">
                                          <dim type="top">38</dim>
                                          <dim type="bottom">66</dim>
                                          <dim type="left">14</dim>
                                          <dim type="right">43</dim>
                                          <dim type="intercolumn">15</dim>
                                        </dimensions>
                                        <note>These first dimensions are for text 1, taken from <locus target="#6r"/></note>
                                        <dimensions unit="mm">
                                          <height>204</height>
                                          <width>188</width>
                                        </dimensions>
                                        <dimensions type="margin" unit="mm">
                                          <dim type="top">35</dim>
                                          <dim type="bottom">83</dim>
                                          <dim type="left">11</dim>
                                          <dim type="right">58</dim>
                                          <dim type="intercolumn">17</dim>
                                        </dimensions>
                                        <note>These second dimensions are for text 2, taken from <locus target="#91r"/></note>
                                </layout>
                            </layoutDesc>
```

so layouts must be split. done

**Comment by vitagrazia81** [comment]
Thanks :-)
