### ISSUE TITLE
Update textpart IDs of Dǝrsāna Mikāʾel in manuscript records

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#2723]
I am looking for the ID of the miracle of Miracle of the Three Youths in the Furnace (Miracles of Michael). This is encoded as LIT1295Dersan#CommemorativeTahsas in BAVet82, but the xml:id in question does not exist anymore in LIT1295Dersan. 
Do you happen to know which ID corresponds to it now? 
If there is no corresponding ID anymore, should it be added as a textpart to LIT1295Dersan or should an independent record be created?
@CarstenHoffmannMarburg @MassimoVilla

**Comment by thea-m** [comment]
@CarstenHoffmannMarburg I noticed that xml:ids which had previously existed in LIT1295Dersan now are not there anymore. This means that all references to them in manuscript records are now invalid. Have there been discussions on how to update these manuscript references? I could not see any in the PR, but it's possible that I missed it.

**Comment by MassimoVilla** [comment]
As far as the BAV manuscripts of the Dərsāna Mikāʾel are concerned, I am going to open a new branch and update all IDs according to the new div IDs now given in LIT1295Dersan, but also all the other records of MS witnesses to the Dərsāna Mikāʾel should be updated accordingly.

**Comment by CarstenHoffmannMarburg** [comment]
> @CarstenHoffmannMarburg I noticed that xml:ids which had previously existed in LIT1295Dersan now are not there anymore. This means that all references to them in manuscript records are now invalid. Have there been discussions on how to update these manuscript references? I could not see any in the PR, but it's possible that I missed it.

I will update BMLacq776. Massimo wanted to update the BAV manuscripts, that he has been working on lately. For the others, we do not have an agreement. I suppose, this will be my task, because, I updated LIT1295Dersan recently.

**Comment by thea-m** [comment]
That would be great :) I know it is a huge task, but I think it is probably easier for you than anybody else, because you already know the texts.

**Comment by eu-genia** [comment]
@CarstenHoffmannMarburg yes thank you actually this should have been one workflow, any change in work IDs (sub-IDs included) means simultaneous update of all records where these IDs (or sub-IDs) have been used. Thank you.

**Comment by CarstenHoffmannMarburg** [comment]
At the moment the work is not displayed in the app. I can find only the text for the 'Introduction to the work' and the 'Admonition for Ḫǝdār' on the website. Where are the other textparts? What was wrong with the latest pull request?

![grafik](https://github.com/user-attachments/assets/0227713c-0584-480a-a0f9-ed0860fff2f7)

**Comment by CarstenHoffmannMarburg** [comment]
> @CarstenHoffmannMarburg yes thank you actually this should have been one workflow, any change in work IDs (sub-IDs included) means simultaneous update of all records where these IDs (or sub-IDs) have been used. Thank you.

It is difficult to handle more than 90 very long manuscript records in one workflow.

**Comment by CarstenHoffmannMarburg** [comment]
> I am looking for the ID of the miracle of Miracle of the Three Youths in the Furnace (Miracles of Michael). This is encoded as LIT1295Dersan#CommemorativeTahsas in BAVet82, but the xml:id in question does not exist anymore in LIT1295Dersan.
> Do you happen to know which ID corresponds to it now?
> If there is no corresponding ID anymore, should it be added as a textpart to LIT1295Dersan or should an independent record be created?

@thea-m The textpart, that you are looking for is not in the EOTC version, that I took as a basis for my latest rework of LIT1295Dersan. I deleted this textpart, because I could not identify it or because I wrongly identified it with another miracle or commemorative note. However, I will rework LIT1295Dersan in a new pull request and add this textpart, which is attested in BMLacq776. I gave it the subID 'CommemorativeFurnace':
```
<div type="textpart" subtype="chapter" xml:lang="gez" xml:id="CommemorativeFurnace">
                  <label xml:lang="en">Commemorative on Babylon</label>
                  <note>This Commemorative note is attested in <ref type="mss" corresp="BMLacq776 BAVet82"/>, but is not transmitted in
                     <bibl><ptr target="bm:2006DersanaMikael"/></bibl>.</note>
                  <div type="textpart" subtype="incipit">
                     <ab>በስመ<supplied reason="omitted">፡ </supplied>አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩አምላክ፡ 
                        አመ<supplied reason="omitted">፡ </supplied>፲ወ፪፡ ለታኅሣሥ፡ በዘቲ፡ እለት፡ እለተ፡ በአሉ፡ ለቅዱስ፡ ሚካኤል፡ ሊቀ፡ መላእክት፡ እስመ፡ በዛቲ፡ እለት፡ 
                        ፈነዎ፡ እግዚአብሔር፡ ሀበ፡ ሀገረ፡ በቢሎን፡ ወኮነ፡ ራብአየ፡ ገጽ፡ ምስለ፡ ፫ደቂቅ፡ 
                        <persName ref="PRS11288AnAzMi">አናንያ፡ ወአዛርያ፡ ወሚሰኤል፡</persName> 
                        ውስተ፡ እቶነ፡ እሳት፡ ሶበ፡ ገደሮሙ፡ ናቡ፡ ክዳነ፡ ጸር፡ ንጉሠ፡ ባቢሎን፡ ወተለአለ፡ ነበልባለ፡ እሳት፡ መጠነ፡ ፵ወ፱በእመት፡</ab>
                  </div>
                  <div type="textpart" subtype="explicit">
                     <ab>ወበዝንቱ፡ ተነበዩ፡ ፴ወ፫፡ ቢዜ፡ ከመ፡ ክርስቶስ፡ ይነብር፡ ዲበ፡ ምድር፡ ፴ወ፫ዓመተ፡ ወበእንተዝ፡ ሠርዑ፡ አበዊነ፡ ሐዋርያት፡ ከመ፡ ይትገባር፡ 
                        በአሎ፡ ለቅዱስ፡ <hi rend="rubric">ሚካኤል፡ ሊቀ፡</hi> ሊቀ፡ መላእክት፡ በበ፡ ፲ወ፪እለት፡ ትኅብልናሁ፡ የሀሉ፡ ምስለ፡ ገብሩ፡ 
                        <gap reason="omitted" unit="chars" quantity="5"/> ለዓለ፡</ab>
                  </div>
               </div>
```

**Comment by eu-genia** [comment]
You cannot delete text parts as this is the same as deleting CAe Id that has been used.

**Comment by eu-genia** [comment]
I am sorry if this was not made sufficiently clear

**Comment by CarstenHoffmannMarburg** [comment]
> You cannot delete text parts as this is the same as deleting CAe Id that has been used.

I see, that there is a problem in not doing it simultaneously. I think, it will take several months to update all Dersana Mikael manuscripts. Do you think, it is better to do it one by one as fast as possible or do think, the latest merge of LIT1295Dersan should be undone, if that is possible?

**Comment by eu-genia** [comment]
We can easily restore an earlier version at any time. The main issue remains to have independent IDs for miracles and homilies that appear also in other collections such as the Miracles of St Michael etc and clarify relations. I do not think this has been done.

**Comment by eu-genia** [comment]
Dear @CarstenHoffmannMarburg I suggest that I
1) restore the former version
2) adjust the xml:id to have no names of months in them (it would take me probably 1 hour to change them in the file and in all the associated manuscript records, simply replacing the reference everywhere every time I change it in the file, this is the way I always do it when updating IDs, whether deleting/merging/changing, it is always the same - search in Oxygen in all occurrences and replace just takes 1 click for each xml:id)
3) then you can ADD textparts that you found in the edition that were not there, but never DELETE textparts with xml:id unless you can be 100% sure that these have never been pointed to. deleting an internal xml:id is the same as deleting an entire record in this sense, you risk to render links invalid

Main task that you had agreed to take over was to examine the miracles and homilies in the Dersana set and in the Miracles set and see if there are matches (https://github.com/BetaMasaheft/Documentation/issues/2361), if yes, all texts with varying constellations and circulations must receive upper level CAe IDs and corresp must be added to them. Please confirm that this is what you are going to do or if someone else should have a look. Thank you!

**Comment by eu-genia** [comment]
Just to explain: I am not going to deal with 90 long manuscript records. What I will do is
When in the record LIT1295Dersan I change `xml:id="HomilyHedar`" to `xml:id="HomilyTimothy"` then at the same moment I replace in all occurences in all the other manuscripts and works the string `ref="LIT1295Dersan#HomilyHedar"` with the string `ref="LIT1295Dersan#HomilyTimothy"`. And so on.

**Comment by CarstenHoffmannMarburg** [comment]
> Just to explain: I am not going to deal with 90 long manuscript records. What I will do is When in the record LIT1295Dersan I change `xml:id="HomilyHedar`" to `xml:id="HomilyTimothy"` then at the same moment I replace in all occurences in all the other manuscripts and works the string `ref="LIT1295Dersan#HomilyHedar"` with the string `ref="LIT1295Dersan#HomilyTimothy"`. And so on.

I understand that you want to exchange the sub-IDs in all manuscript records for the new IDs, that I gave to the homilies, miracles, commemorative notes and salams in each month. What I do not understand is, why you want to restore the old version then. If you can replace all the old sub-IDs for the new sub-IDs within one hour, it would be useful to have the new version of LIT1295Dersan in the same moment as this change has been done.
Furthermore, I want to make some remarks on problems that may occur:
First, exchanging the ID was not the only feature or reworking, that I did. Another one is, that I singled out the first one or two sentences of every homily to be independent as Admonition (Admonition for Hedar, Admonition for Tahsas, etc). This restructuring made sense to me, because these admonitions refer to the Dersan of each month but not the homily infact. However, in the manuscript records, this change needs to be reflected in new ms-Items for each month, what is a little cumbersome to do for 90 records, especially if the locus needs to be adjusted and checked in each case. It is a question, whether this restructuring with sub-IDs for the admonitions are worth doing this effort and should be kept or if the old structure should be restored.
Secondly, I am concerned, that at least some records define a "Homily of Hedar" simply because it is place inside the readings for Hedar, no matter whether they are identical with what we had defined as HomilyHedar in the old LIT-record. I assume, that such mistakes will be perpetuated, if the IDs are quickly exchanged for new ones (as e.g. HomilyTimothy). The mistake will get even more obvious, because users will be wondering, if they have a look into a homily, which is labelled as "Homily by Timothy" and do not find any Timothy in it. One can revise the records after changing the IDs, but this will still take a lot of time.

**Comment by eu-genia** [comment]
Of course it would be useful, this is what I have done. It has taken somewhat longer as I also edited all the individual homilies. More to be done. I have also replaced some of the IDs in BLorient4849 and created several new textparts as BLorient4849 has some miracles that were not present in the general record (Bula Abib for example)

**Comment by eu-genia** [comment]
The admonitions are parts of the Dersanat. They have already been edited as such and included in the individual homilies as well.

**Comment by eu-genia** [comment]
Let us all try to be careful that whatever we do the most important thing is not to harm the things that have been previously done.

**Comment by eu-genia** [comment]
Updated (apart from the ones in personal branches)
