### ISSUE TITLE
Serate menkusenna 

### ISSUE THREAD

**Issue by MagdaKrzyz** [SChAth/ScAthiop#2737]
The textual tradition of the text "Serate minkussina" is very complex. We have now 3 records on the work, including one general record. I hoped to contribute to the description of the "Śǝrʿāta śimata mǝnkʷǝsǝnnā" LIT2350serata and provide its subsections but it seems that only the first part (some 30 fols.) occurs also in some of the witnesses. In BNFabb71 (Denis, you have described it) from fol. 41 there "Śǝrʿāta asira mǝnkʷǝsǝnnā". 
 
Conclusion, I will not try to disentangle this knot since it would take too much time and leave it for the person who contacted Denis.

**Comment by thea-m** [comment]
@MagdaKrzyz , you had opened this issue in the repository "Manuscripts", which is very logical and intuitive, but for practical reasons, all issues, regardless to what types of records they refer to, should be opened in the repository "Documentation":
![image](https://github.com/user-attachments/assets/0be6bb66-2db6-47d5-af0b-6ce7841c889b)

It is easier to search for topics etc when everything is collected in one place.
 I moved your issue to the correct place, you need to do nothing now, I just write for your information :)

**Comment by eu-genia** [comment]
I am not quite sure what you are asking me to do (assign issue = ask someone to fix a problem or answer a question).

If there is a part of a work with an independent circulation that so far has no independent ID then the best practice would be to create a new Clavis ID for this text and include a relation specifying that can be a part of a bigger text.

If you are fine with continuing with a general record for the time being and no refining is necessary then this issue is not needed and can be closed.
