### ISSUE TITLE
citing manuscripts and inscriptions

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#283]
The correct way of reference to manuscripts (in citation for sure, and if possible in the title) should be
Town, Library, Collection Shelfmark
e.g.
London, British Library, Oriental 800
Paris, Bibliothèque nationale de France, Éthiopien 5
Vatican City, Biblioteca Apostolica Vaticana, etiopico 1
etc
we might have to modify something in the description to ensure this. 
These are the rules we follow in all publications.

**Comment by PietroLiuzzo** [comment]
please agree on how to print titles and references and provide an example in order to adjust the visualization. all the information is already there. which information is missing in the data which you think should be added otherways I do not think we need schema or file strcuture changes?

**Comment by PietroLiuzzo** [comment]
#269

**Comment by abausi** [comment]
Dear all,

I agreef for this with the solution suggested by Zhenia, that is in 
keeping with all our publications.

Best,

Alessandro

Il 27.01.2017 14:45, Pietro Liuzzo ha scritto:

**Comment by eu-genia** [comment]
the information is there but under idno at the moment we repeat the abbreviated library sigla and the collection, it is not just the number - this may have to be modified.

**Comment by abausi** [comment]
We still need to discuss this together, I understand this is complex, 
but I cannot propose now any simple solution.

Alessandro

Il 27.01.2017 15:12, Pietro Liuzzo ha scritto:

**Comment by PietroLiuzzo** [comment]
I have started to update the titles. For the shelfmark I am currently taking the string after the first space where there are spaces. this means that for ES manuscript I take all, and for most of the others the string after the abbreviation. This does not work for all of course but I think it is easier to make the idno consistent this way rather than changing all the idno already there. no objection of course if you decide to alter all the data in the records to have only the shelfmark in idno. 

Cambridge, Bible Society's Library, Mss 169
Vatican, Biblioteca Apostolica Vaticana, Aeth. 1 (NOTE in Institution record no settlment info!)
Paris, Bibliothèque nationale de France, Éthiopien 120
Oxford, Bodleian Library, Clarke Or. 2

Where a stub has been created and no repo info are provided there will be a note of this kind
no repository data for RIE189

Always speaking only of titles, this notation, against our data structure is quite expensive as it requires looking into several records (the place name is in place record or in geonames, the institution name is in the institution record and the name of the manuscript in the ms record), and each of these might be not there or wrong, thus the app takes even longer than before. For ES manuscripts the first part of the reference is also to be defined: for institution pointing to a settlement I can take the title of that settlement but for institutions which have more settlement elements with a specific type or a composite settlement information, I don't know which one you want to preserve in the citation. 

wäräda Gulo Mäkäda, ṭabiya Kǝsad Maʿǝtäb, qušät Mǝdrä Ruba/Däbrä Zäyt, Däbrä Zäyt Qǝddǝst Maryam, DZ-001 is a case where there is still one settlement undivided
Gulo Maḵadā, ʿĀddi Qolqwāl Giyorgis, AQG-001 is a case where the settlment element have been divided and I take the information from the first of them in the tree

This will have to be handled differently, possibly in a javascript function rather then the current xquery. 

The references, e.g. witness and  ref[@type='mss'] elements do not use xquery but xslt as they might appear in mixed content elements and thus need to be processed using apply-template function in xslt for consistency. this also might be made omogeneous with a javascript function performing this action.

**Comment by eu-genia** [comment]
Most of the ES mss still have to be corrected by hand, AQG is a good test - Gulo Maḵadā, ʿĀddi Qolqwāl Giyorgis, AQG-001 is correct.

**Comment by PietroLiuzzo** [comment]
Lists filters and all refs report titles pers name and placenames work this way . Time line indexes and relations still to be a updated

**Comment by eu-genia** [comment]
the problem is now for RIÉ inscriptions. these should appear as RIÉ 187 etc.

**Comment by PietroLiuzzo** [comment]
I have added a rule so that if @form is Inscription the idno is taken. ok?

**Comment by PietroLiuzzo** [comment]
@eu-genia if titles and ref view is now as required, please close issue.

**Comment by eu-genia** [comment]
this is ok for the title but now for the inscriptions we do not see the repository information at all, and we need it somewhere

**Comment by PietroLiuzzo** [comment]
If encoded like ms there should be no difference. Could you check? I cannot now open the file. Please let me then know what is the difference in encoding to evaluate changes

**Comment by PietroLiuzzo** [comment]
I correctly see aksum in the header as encoded. Perhaps I did not understand where is the issue here

**Comment by eu-genia** [comment]
was imprecise sorry: we see the repository but not the location, and it is equally important.
in mss we see e.g. as the title London, British Library, Oriental *** and to the right in green "British Library"
in inscriptions e g RIE232 we now see RIÈ 232 as the title and to the right in green just "Dabra Libanos" there is no information on the place of the repository. Maybe we can repeat it for all in the right box. (We do need Ham, Dabra Libanos, as there are other Dabra Libanos around)

**Comment by eu-genia** [comment]
can we also by default see the "Given summary of contents" tab for the Inscriptions?

**Comment by eu-genia** [comment]
(links are not clickable in the Given summary of contents)

**Comment by DenisNosnitsin1970** [comment]
I find "Gulo Maḵadā, ʿĀddi Qolqwāl Giyorgis, AQG-001" apt, perhaps we should consider the following: wäräda Gulo Mäkäda is a recent formation, it exists in its current borders maybe 30-40 years. In fact we do not know. Also I am not sure that it will exist in the current borders in 20-30 years. Another thing - what is today wäräda is equivalent to awräjja of the Emperial Ethiopia. What is not "tabiya" in ES mss, was "wäräda" in the Emperial Ethiopia. There are also some other differences. Does it make any difference?

**Comment by PietroLiuzzo** [comment]
Please make a new issue for given summary

**Comment by PietroLiuzzo** [comment]
The place shown in the title for mss is that reported in the ins record under settlement as discussed. I will print it also on the repo info as in the title of mss for all records

**Comment by eu-genia** [comment]
yes but there is also the settlement for the institutions used for the inscriptions. 
it is correctly not shown any more in the title (it used to be until the change) but the problem is it is not shown anywhere at all - the best would be to repeat it with the institution (now printed in the green box)

**Comment by PietroLiuzzo** [comment]
now the green button for the institution always prints place and institution. I am not sure this is a desirable behaviour for all.

**Comment by eu-genia** [comment]
it does help

**Comment by PietroLiuzzo** [comment]
cool, then please close issue if this is solved
