### ISSUE TITLE
Transcription transformation (long a)

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#326]
A word like aʿǝban is currently transformed as ʾāʿǝbān instead of ʾ**a**ʿǝbān.
In other words, initial /a/ is not long (አእባን፡, not ኣእባን፡).

The same applies for analogous cases with initial /a/, such as Mäṣḥetä ʾamin, which currently becomes Maṣḥeta ʾāmin instead of Maṣḥeta ʾamin, or again Śǝrʿatä abäw which is transformed into Śǝrʿāta ʾābaw instead of Śǝrʿāta ʾabaw (ሥርዓተ፡ አበው፡).

**Comment by thea-m** [comment]
When ba, wa, la, za at the beginning of a word precede two consonants, they are never a preposition, so it would be timesaving if the app would not suggest hyphenation in these cases

**Comment by thea-m** [comment]
Could ʾǝm be added to the list of prepositions?

**Comment by PietroLiuzzo** [comment]
@thea-m please provide sample input and desired output

**Comment by PietroLiuzzo** [comment]
@MassimoVilla this looks to me as the expected behaviour if you enter text which is partially adhering to conventions. The input expects a for a long a and does is job on it correctly. If thosé are the old conventions I fail to understand why the first is short and the second a is long when there is no umlaut. Or a is with umlaut only sometimes for first order?  If so when in the old conventions? If this can be a rule that for example a is always short in the first syllable then I can do this update.

**Comment by thea-m** [comment]
ʾǝmqālāta - ʾǝm-qālāta
For Massimo's case: the transformation is of course performed correctly, but intitial ʾa (without Umlaut because of the preceding ʾ) always stands for the first order (አ... not ኣ...)

**Comment by PietroLiuzzo** [comment]
Thanks. I need an example of the two consonants if possible please.

**Comment by PietroLiuzzo** [comment]
input | output
---|---
Mäṣḥetä amin | Maṣḥeta ʾamin
Śǝrʿatä abäw | Śǝrʿāta ʾabaw
aʿǝban | ʾaʿǝbān

**Comment by thea-m** [comment]
Bärbara - Barbārā
Bärtolomewos - Bartolomewos

**Comment by PietroLiuzzo** [comment]
@thea-m ʾǝmqālāta - ʾǝm-qālāta is the input according to old conventions? I would expect ǝmqalatä

**Comment by thea-m** [comment]
you're right, I was mixed up

**Comment by PietroLiuzzo** [comment]
no worries, that's why we need a software :D

**Comment by PietroLiuzzo** [comment]
see https://github.com/SChAth/ScAthiop/issues/326#issuecomment-281139190
and test with other cases.
Please let me know if there are other rules to satisfy
