### ISSUE TITLE
online DL Abbrev.: "Greg. Ep." - help in specification?

### ISSUE THREAD

**Issue by fitawari** [SChAth/ScAthiop#370]
- there is one entry in online DL for the abbreviation "Greg. Ep." (lemma: ሰንበታዊ) 
- a speculative reading is: Epistle/letter of Abba Gorgorius to Hiob Ludolf, but it could be much else (writing of St. Gregory?) 
- following the idea of this reading: if printed in Ludolf's commentary, no LIT entry possible; about the ms. of the letter, I do not know much; any hint is welcome!

**Comment by MassimoVilla** [comment]
This is the text of the letter sent by Abba Gorgoryos to Hiob Ludolf in 1649 (8 August), and published by the latter in his _Commentarius_ on pp. 35ff.: http://reader.digitale-sammlungen.de/de/fs1/object/goToPage/bsb10867109.html?pageNo=78.
Unfortunately, I have not found any occurrence of ሰንበታዊ, but it might be due to my negligence.
It is not the only letter sent by Gorgoryos to Ludolf: on EAE vol. II, p. 855a I read that another epistle was sent on 6 October 1650.

**Comment by PietroLiuzzo** [comment]
There is no need to align the this if it is not a text in bm.
