### ISSUE TITLE
creating IDs for magic prayers

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#371]
While encoding the scrolls of Ullendorff's catalogue (see for example, BDLaethf4, BDLaethf5, BDLaethf6 ) I am wondering how to deal with the magic prayers they contain (only described by their incipit and occasionally general content):
- it doesn't seem to me that all of them are "works" in our definition (fixed contents and a precise sequence) - even if the incipit mentioning the illness/demon is the same in several prayers, the text probably is not identical
- are these, in fact, narrative units in the sense that they belong to a certain genre (for example, ጸሎት፡ በእንተ፡ ሕማመ፡ ቍርጸት፡) while the text can differ from manuscript to manuscript?

**Comment by DenisNosnitsin1970** [comment]
It seems that many of these prayers may have similar incipits, but widely diverging "text bodies". We cannot say, for the moment, if these discrepancy is the result of a long textual transmission of a limited number of these prayers (rather not, because we do not have very old magic prayers), or they are just so fluid by the nature of its genre, which do not require strickt form and fixed narrative, rather the presense of some specific elements. To my opinion, these texts can be considered independent works (each with its own id?) unless someone starts to find relations between them (there may be cases where one can recognize that one scroll was used as exemplar for producing another one). There are some elements which, to my opionion, can help for identifying the prayers. First, if there is a chance, one can record a bit more of the incipit /explicit. Second, the identification of the motifs used in the prayers can be helpful: the story of Susenyos and Werzilya, or Jesus and disciples on the sea of Tiberias, and some others. They will help to group the prayers. Third-fourth, the presense of the strings of "asmat" ("hidden names" of God), and the strings of "qalat" (magic words).  For sure, some of the prayrs will be found copied in codices (one more point for considering them independent units?)
