### ISSUE TITLE
illumination/picture

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#488]
In his catalogue, Ullendorff differenciates illuminations and pictures (see for instance BDLaethc2) - to which of the Ethiospare terms do these correspond? (Miniature, illustration?)

**Comment by DenisNosnitsin1970** [comment]
I wished to think his "illumination" corresponds to miniature (coloured), and "picture" is monochrom drawing, but it is not because elsewhere he uses the term "drawing". Is for him "illumination" smth that "illuminates" the text? on ff. 33-58,  there is Gospel of Mark, and it is preceeded by a miniature of Mark (=illumination). But on f. 32, there is a redundant image of Mark, which does not illuminate anything (=picture). But in the description on p. 77 the images are described in an apparently different way. No clear!

**Comment by thea-m** [comment]
thank you, that's what I feared. I kept the type now "unspecified" and added a comment - hopefully we will be able to check this with the manuscript one day
