### ISSUE TITLE
Encyclopaedia or Dictionary - Zotero classification

### ISSUE THREAD

**Issue by SophiaD-M** [SChAth/ScAthiop#579]
My question concerns the classification of Encyclopaedia or Dictionary entries - what defines them?

This for example: https://www.zotero.org/groups/358366/ethiostudies/items/itemKey/I2V5U3T6/q/mallett
is a bibliographic History, would entries be considered Encyclopaedia, or Dictionary? 
A related question would be for example the "Kleines Wörterbuch des Christlichen Orients", http://www.worldcat.org/title/kleines-worterbuch-des-christlichen-orients/oclc/4568948, which is not a Dictionary strictly speaking. How might entries therein be classified?

**Comment by abausi** [comment]
There is certainly a degree of arbitrariness, but what mostly counts is that a work is organised in more volumes (as usually happens with large encyclopaedias) or not. Styles (Chicago, Oxford etc.) may vary much in how to represent encyclopaedic entries, and this is one more aspect. To mark anything as "encyclopaedic entry" when entering the entry, can help in marking it in a way of its own when necessary. But this is not mandatory, In the case  of the "Kleines Wörterbuch", I would not definitely mark it as an encyclopaedia, and its entries as well. But the way in which the single entries will be quoted in a given contribution, particularly when its entries are quoted often, is another matter.

**Comment by SophiaD-M** [comment]
Thank you Alessandro.
Just to make sure - this would be correct?
https://www.zotero.org/groups/358366/ethiostudies/items/itemKey/7TZJR2KB/q/Damru

**Comment by abausi** [comment]
There are two options: either you indicate the volume (as you did) in the title of the encyclopaedia (which is more simple for aspetcs of formatting), or you enter the number (in Roman numbers, at least for HLCES) in the field "volume", like this: "III: (1050-1200)"; encyclopaedia title then would be only: "Christian-Muslim Relations. A Bibliographical History". I think this would be more correct, since this is the title of the encyclopaedia, and the date only specifies what is in volume III. The encyclopaedia entry appear to have been so conceived in Zotero and one should probably follow this solution to optimize Zotero`s functions. I remind that it is very impoprtant to insert correctly the characters fro which I sent you the Keyman update (i.e. write opening and closing simple and double quotation commas, like this ‘ and ’ and not ', and “ and ”, and not ").

**Comment by SophiaD-M** [comment]
Thank you
