### ISSUE TITLE
large quires and quires contained in quires diagrams

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#88]
(1) for quires larger than 10 ff the bottom of the image is hidden
(2) works well only if the collation is given once for an entire ms, did not work when there were two collation lists for two msParts (as in ESmr001)
(3) the complex situation of a quire inserted into another quire is not visualized
(in ESmr001 we have quire X with ff. 92-- 93-94 --99, and quire XI with ff. 95-- 96-97 --98 inserted into quire X)

**Comment by eu-genia** [comment]
maybe if a way is found to resolve (3) it would be also necessary to show all leaf numbers, not just first and last

**Comment by PietroLiuzzo** [comment]
1. is a known limit of VisColl as per their description.
1. this is a visualization problem in the html I think. it should be fine now. Nevertheless I had to make up the example, since I did not find the situation described in the sample file named.
1. I did not see an examle of this in VisColl documentation and examples, I will enquire.

**Comment by PietroLiuzzo** [comment]
could these be described as added leaves?

**Comment by eu-genia** [comment]
in mr001 it is an inserted quire (composite ms)
but the collation is wrong there are two stubs at the end
97---- -----98
96---- --
95---- --
(i am not sure how to describe the stubs in the xml, something is wrong
this is inserted inside another quire, between 94 and 95

**Comment by PietroLiuzzo** [comment]
the case of ESmr001 can be treated a separate quire. the leaf numbering will be incorrect in the graph for this reason as it is computed and not taken from given data. an alternative description could be to treat all as added leaves, although this is not correct as the quire and not the single leaves are added.

**Comment by PietroLiuzzo** [comment]
I have also enlarged the area for the diagram, to allow for more leaves.

**Comment by PietroLiuzzo** [comment]
I suggest this solution, to have a non misleading representation

````xml
<item xml:id="q11" rend="withInsertion" corresp="#q12">
     <dim unit="leaf">4</dim>
      <locus from="92r" to="99v"/>
       X (<note>between <locus target="#94">94v</locus>
       and <locus target="#99"> 99r</locus>: <ref target="#q12">the
     second codicological unit</ref></note>) 
</item>
<item xml:id="q12" rend="inserted"  corresp="#q11">
     <dim unit="leaf">4</dim>
    <locus from="95" to="98"/>
    XI (s.l.: 2, stub after 4; 1, stub after 4)
</item>
````

The changes I made here are basically that I added a @rend attribute to the quires included into one another which takes two values, inserted or withInsertion. This determines that the first and last leaf do not take a computed value which is sequential to the quire description, but the value of the first `locus` in the item, which thus needs to have the extremes of the quire, so, as above `<locus from="92r" to="99v"/>` this remains true, and is then clarified in the note. The view will then also show this label, as well as the correct initial and final numbers for the leaves of the quires in question. This is indeed suboptimal, but I hope serves well for now. Please see ESmr001 to view the example preview although due to a different issue, no number is visualize at the beginning of q12.

**Comment by eu-genia** [comment]
i think this is workable for now, with the @rend, thank you
