### ISSUE TITLE
collation error for quires with odd quantity and no indication of singleton/stub positions

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#99]
BAVet2 does not get preview because of an error (cannot convert to integer)

**Comment by PietroLiuzzo** [comment]
this is due to lack of information in the collation. a quire with seven leaves without any indication of where the singleton and the stub are.  if you for example add   "1 stub after 7" within q7 the preview will do its job. please let me know how you want such cases to behave as a default fallback.

**Comment by eu-genia** [comment]
ok then this particular ms is to try for @MassimoVilla to fix

**Comment by PietroLiuzzo** [comment]
I have updated the guidelines with the available options for quire descriptions, now handled in the diagram visualization. Most of the cases where ES records give problems in viewing are related to a similar issue.
